### ISSUE TITLE
Specify package version

### ISSUE THREAD

**Issue by HirotoShioi** [srid/reflex-dom-pandoc#4]
Please specify the version of the packages so that it can be stably compiled.

Hello! I was trying to compile this project but failed to do so due to the compiler error.

```
src/Reflex/Dom/Pandoc/PandocRaw.hs:62:18: error:
    • Couldn't match type ‘[Char]’ with ‘Text’
      Expected type: Text
        Actual type: String
    • In the second argument of ‘elClass’, namely
        ‘("pandoc-raw " <> format)’
      In the expression: elClass "pre" ("pandoc-raw " <> format)
      In the expression: elClass "pre" ("pandoc-raw " <> format) $ text s
   |
62 |   elClass "pre" ("pandoc-raw " <> format) $ text s
   | 
```

I believe this is due to the fact that the packages that my machine used to compile this project is different from the ones that other people are using. Specifying the package version should resolve this issue.

There are two ways of doing this, either you specify them within `.cabal` file or you run (`cabal freeze`](https://www.haskell.org/cabal/users-guide/nix-local-build.html#cabal-v2-freeze). Either should be fine.

**Comment by srid** [comment]
PR welcome on that [the former approach, not cabal freeze]! 

FWIW, I build this package through [reflex-platform](https://github.com/reflex-frp/reflex-platform) (see also [here](https://github.com/srid/neuron#developing-on-reflex-dom-pandoc)) which already has the package set configured appropriately for reflex apps.

**Comment by srid** [comment]
This is what cabal freeze generates, for what it's worth: https://gist.github.com/srid/bea57d6e0f4466ce4bff2740ac8743a1
